language: node_js

node_js:
 - "0.10"

services:
 - mysql

notifications:
  email:
    - dcoates@mozilla.com
    - achilton@mozilla.com
    - jrgm@mozilla.com
    - rfkelly@mozilla.com
  irc:
    channels:
      - "irc.mozilla.org#fxa"
    use_notice: false
    skip_join: false

install:
  - npm install --no-optional

before_script:
  - mysql -e 'DROP DATABASE IF EXISTS fxa'
  - npm run outdated
  - grunt validate-shrinkwrap

script:
  - npm test

