language: node_js

node_js:
 - "0.10"

# workaround for obsolete `temp` module 0.6
env:
  global:
    - TMPDIR=/tmp

services:
 - mysql

notifications:
  email:
    - dcoates@mozilla.com
    - achilton@mozilla.com
    - jrgm@mozilla.com
    - rfkelly@mozilla.com
  irc:
    channels:
      - "irc.mozilla.org#fxa"
    use_notice: false
    skip_join: false

install:
  - npm install --no-optional

before_script:
  - mysql -e 'DROP DATABASE IF EXISTS fxa'

script:
  - npm test

